[package]
name = "grepr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7.1"
clap = "2.33.0"
glob = "0.3.1"

[dev-dependencies]
assert_cmd = "1"
